# Generated by Django 5.0.7 on 2024-08-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_organization",
            field=models.BooleanField(default=False),
        ),
    ]
